# This file is to manage configuration parameters
# of the script plot_csvs.py

# Note: Make configuration from top to bottom

# First: Select model
model: 'MOMF' # two options: 'MOMF' or 'BULAC'

# If model is MOMF, select what tier use
tier: '1' # two options: '1' or '3a'

# Second: Select folders
tier1_dir: '\t1_confection\Executables' # Don't change
tier3a_dir: '\t3a_experiments\Experiment_1\Futures' 
excel_data_file_dir:  '\t3a_experiments\Experiment_1\Futures\'
vis_dir: 'Visualizations' # Only changes y you want to change the folder name where save png plots files
out_dir: '/Outputs' # Don't change
dir_main_script_yaml: '../config_main_files'
info_filename: 'Informacion_preliminar_graficacion.txt'

# Third: Fill with scenarios
scens: ['BAU', 'LTS']

# Fourth: Select if you want see information
# Recomendation: Ever put like true in the first run and run now
info: False

# Fifth: Set years for plots
start_year: 2020 # This is the firts year for the ticks in the plot
separation_years: 5 # This is the gap  between each tick in the plot

# Sixth: Fill list of each parameter with technologies you want to plot
# Year to apply discount rate
year_apply_discount_rate: 2024

#Check the second word of names of the list are the same than the scenario
# BAU
techs_BAU_AccumulatedNewCapacity: [[], []]
techs_BAU_AnnualEmissions: [[], []]
techs_BAU_AnnualFixedOperatingCost: [[], []]
techs_BAU_AnnualTechnologyEmission: [[], []]
techs_BAU_AnnualTechnologyEmissionPenaltyByEmission: [[], []]
techs_BAU_AnnualTechnologyEmissionsPenalty: [[], []]
techs_BAU_AnnualVariableOperatingCost: [[], []]
techs_BAU_CapitalInvestment: [[], []]
techs_BAU_Demand: [[], []]
techs_BAU_DiscountedSalvageValue: [[], []]
techs_BAU_DiscountedTechnologyEmissionsPenalty: [[], []]
techs_BAU_NewCapacity: [['DIST_DSL', 'DIST_GSL'], []]
techs_BAU_ProductionByTechnology: [[], []]
techs_BAU_RateOfProductionByTechnology: [[], []]
techs_BAU_RateOfProductionByTechnologyByMode: [[], []]
techs_BAU_SalvageValue: [[], []]
techs_BAU_TotalCapacityAnnual: [[], []]
techs_BAU_TotalDiscountedCost: [[], []]
techs_BAU_TotalDiscountedCostByTechnology: [[], []]
techs_BAU_TotalTechnologyAnnualActivity: [[], []]
techs_BAU_UseByTechnology: [[], []]
techs_BAU_Capex${year_apply_discount_rate}: [[], []] # Do not change ${year_apply_discount_rate}, the script update automatically with year defined before
techs_BAU_Externalities${year_apply_discount_rate}: [[], []]
techs_BAU_FixedOpex${year_apply_discount_rate}: [[], []]
techs_BAU_Opex${year_apply_discount_rate}: [[], []]
techs_BAU_VarOpex${year_apply_discount_rate}: [[], []]

# NDP
techs_NDP_AccumulatedNewCapacity: [[], []]
techs_NDP_AnnualEmissions: [[], []]
techs_NDP_AnnualFixedOperatingCost: [[], []]
techs_NDP_AnnualTechnologyEmission: [[], []]
techs_NDP_AnnualTechnologyEmissionPenaltyByEmission: [[], []]
techs_NDP_AnnualTechnologyEmissionsPenalty: [[], []]
techs_NDP_AnnualVariableOperatingCost: [[], []]
techs_NDP_CapitalInvestment: [[], []]
techs_NDP_Demand: [[], []]
techs_NDP_DiscountedSalvageValue: [[], []]
techs_NDP_DiscountedTechnologyEmissionsPenalty: [[], []]
techs_NDP_NewCapacity: [[], []]
techs_NDP_ProductionByTechnology: [[], []]
techs_NDP_RateOfProductionByTechnology: [[], []]
techs_NDP_RateOfProductionByTechnologyByMode: [[], []]
techs_NDP_SalvageValue: [[], []]
techs_NDP_TotalCapacityAnnual: [[], []]
techs_NDP_TotalDiscountedCost: [[], []]
techs_NDP_TotalDiscountedCostByTechnology: [[], []]
techs_NDP_TotalTechnologyAnnualActivity: [['DIST_DSL', 'DIST_GSL', 'DIST_LPG'], ['PJ']]
techs_NDP_UseByTechnology: [[], []]
techs_NDP_Capex${year_apply_discount_rate}: [[], []]
techs_NDP_Externalities${year_apply_discount_rate}: [[], []]
techs_NDP_FixedOpex${year_apply_discount_rate}: [[], []]
techs_NDP_Opex${year_apply_discount_rate}: [[], []]
techs_NDP_VarOpex${year_apply_discount_rate}: [[], []]


# Seventh: Select configuration of plots
visible_legend: True # If you want to see legend box
show_fig: True # If you want to show figure window
save_fig: False  # If you want save figure
plot_type: 'stacked_bar' # If you want stacked bar chart, options available: 'bar', 'stacked_bar'

# Eighth: General variables
# Don't change
df_all: [
  'Parameter',
  'REGION',
  'MODE_OF_OPERATION',
  'TECHNOLOGY',
  'FUEL',
  'EMISSION',
  'YEAR',
  'TIMESLICE',
  'VALUE'
  ]

oner: [
  'REGION',
  'MODE_OF_OPERATION',
  'TECHNOLOGY',
  'FUEL',
  'EMISSION',
  'YEAR',
  'TIMESLICE'
  ]

sets_otoole: [ # B1, em, FRM
  YEAR,
  TECHNOLOGY,
  TIMESLICE,
  FUEL,
  EMISSION,
  MODE_OF_OPERATION,
  REGION,
  SEASON,
  DAYTYPE,
  DAILYTIMEBRACKET,
  STORAGE
  ]